name: Next.js CI TEST

on:
  pull_request:
    branches: [develop, main]
jobs:
  next_js_test:
    name: Run Next.js test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          files: ./coverage/lcov.info
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test